-- vim.cmd "packadd easy-align"
-- return function()
  -- local xmap = e0.xmap
  -- local nmap = e0.nmap
  -- local options = {silent = true, noremap = false}
  -- xmap("ga", [[<Plug>(EasyAlign)]])
  -- nmap("ga", [[<Plug>(EasyAlign)]])
-- end
-- Keybindings
-- local options = {silent = true, noremap = false}
-- map({'x', 'n'}, 'ga', '<Plug>(EasyAlign)', options)
